package nl.mpi.kinnate;

            import nl.mpi.arbil.util.ApplicationVersion;

            public class KinOathVersion extends ApplicationVersion {

            /**
            * GENERATED BY ANT - DO NOT EDIT. See the arbil.xml build script.
            */
            public KinOathVersion() {
            applicationTitle = "KinOath";
            applicationIconName = "/nl/mpi/kinnate/resources/icons/kinoath-stable128x128.png";
            currentMajor = "1";
            currentMinor = "0";
            currentRevision = "30691";
            lastCommitDate = "Last Changed Date: 2012-05-04 17:18:03 +0200 (Fri, 04 May 2012)";
            compileDate = "Mon May  7 16:21:59 CEST 2012";
            fullInfo = "\nPath: ../desktop/src/main/java/nl/mpi/kinnate\nURL: https://svn.mpi.nl/LAT/Kinnate/branches/kinnate.1.0.x/desktop/src/main/java/nl/mpi/kinnate\nRepository Root: https://svn.mpi.nl/LAT\nRepository UUID: d4234c5b-7c33-0410-a85d-91bdcf7faf44\nRevision: 30728\nNode Kind: directory\nSchedule: normal\nLast Changed Author: petwit\nLast Changed Rev: 30691\nLast Changed Date: 2012-05-04 17:18:03 +0200 (Fri, 04 May 2012)\n";
            currentVersionFile = "http://www.mpi.nl/tg/j2se/jnlp/kinoath/kinoath-stable-current.txt";
            }
            }
        