package nl.mpi.kinnate;

import nl.mpi.arbil.util.ApplicationVersion;

public class KinOathVersion extends ApplicationVersion {

    /**
     * GENERATED BY ANT - DO NOT EDIT. See the arbil.xml build script.
     */
    public KinOathVersion() {
    	applicationTitle = "";
    	applicationIconName = "";
    	currentMajor = "";
    	currentMinor = "";
    	currentRevision = "";
	lastCommitDate = "";
	compileDate = "";
	fullInfo = "";
    	currentVersionFile = "http://www.mpi.nl/tg/j2se/jnlp/kinoath/kinoath-testing-current.txt";
    }
}
        