name: generate DMG
on:
  workflow_run:
    workflows: [clean test deploy]
    types:
      - completed
jobs:
  build_dmg:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 30000
        ref: kinnate.1.6.separate-diagram-library
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      - name: Generate DMG
        run: pwd;
              jpackage --app-image ../snapshots/installers/1.6.$(git rev-list --count --all desktop) --type dmg --name KinOathDesktop-1.6.$(git rev-list --count --all desktop) --app-version 1.6.$(git rev-list --count --all desktop) --icon desktop/src/main/resources/nl/mpi/kinnate/resources/icons/kinoath-stable.icns;
              ls -l;
              cp -r KinOathDesktop-1.6.* ../snapshots/installers/;
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../snapshots
        keep_files: true