name: generate DMG
on:
  # workflow_run:
  #   workflows: [clean_test_deploy]
  #   types:
  #     - completed
  push:
    branches-ignore:
     - '**' # disables this job
    branches: [ kinnate.1.6.separate-diagram-library ]
jobs:
  build_dmg:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      - name: Generate DMG
        run: pwd;
              echo "Generate_DMG"
              ls -l;
              ls -l *;
              ls -l */*;
              jpackage --app-image ../snapshots/installers/KinOathDesktop-1.6.* --type dmg --icon desktop/src/main/resources/nl/mpi/kinnate/resources/icons/kinoath-stable.icns;
              ls -l;
              ls -l *;
              ls -l */*;
              #cp -r KinOathDesktop-1.6.* ../snapshots/installers/;
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../snapshots
        keep_files: true